-- SDUI metadata for content and time-settings pages.

INSERT OR REPLACE INTO ui_metadata
  (page_key, node_id, component_type, props_json, parent_node_id, group_direction, order_index, action_type, ref_data_id, allowed_roles)
VALUES
  ('content', 'content.root', 'GROUP', '{"className":"sdui-root"}', NULL, 'COLUMN', 0, NULL, NULL, NULL),
  ('content', 'content.title', 'TEXT', '{"as":"h1","text":"콘텐츠 관리"}', 'content.root', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.lead', 'GROUP', '{"as":"p","className":"lead"}', 'content.root', 'ROW', 1, NULL, NULL, NULL),
  ('content', 'content.lead.text', 'TEXT', '{"as":"span","text":"자료, 메모, 첨부 파일을 사용자 계정에 저장합니다. "}', 'content.lead', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.lead.usage', 'TEXT', '{"as":"span","className":"usage-pill","text":"...","dataset":{"usage":""}}', 'content.lead', NULL, 1, NULL, NULL, NULL),

  ('content', 'content.guest', 'GROUP', '{"as":"section","domId":"guest","className":"panel","hidden":true}', 'content.root', 'COLUMN', 2, NULL, NULL, NULL),
  ('content', 'content.guest.row', 'GROUP', '{"className":"empty-login"}', 'content.guest', 'ROW', 0, NULL, NULL, NULL),
  ('content', 'content.guest.copy', 'TEXT', '{"as":"p","className":"hint","text":"콘텐츠 관리는 로그인 후 사용할 수 있습니다."}', 'content.guest.row', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.guest.login', 'TEXT', '{"as":"span","domId":"guestLogin","text":""}', 'content.guest.row', NULL, 1, NULL, NULL, NULL),

  ('content', 'content.member', 'GROUP', '{"as":"section","domId":"member","className":"kmovement-layout","hidden":true}', 'content.root', 'ROW', 3, NULL, NULL, NULL),
  ('content', 'content.form.panel', 'GROUP', '{"as":"section","className":"panel"}', 'content.member', 'COLUMN', 0, NULL, NULL, NULL),
  ('content', 'content.form.head', 'GROUP', '{"className":"result-head"}', 'content.form.panel', 'ROW', 0, NULL, NULL, NULL),
  ('content', 'content.form.title', 'TEXT', '{"as":"div","domId":"formTitle","className":"field-label","text":"새 콘텐츠"}', 'content.form.head', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.form.new', 'BUTTON', '{"domId":"btnNewPost","className":"btn btn-ghost btn-small","text":"새 글"}', 'content.form.head', NULL, 1, 'NEW_CONTENT_POST', NULL, NULL),
  ('content', 'content.form.meta', 'GROUP', '{"className":"meta-grid"}', 'content.form.panel', 'ROW', 1, NULL, NULL, NULL),
  ('content', 'content.form.titleLabel', 'GROUP', '{"as":"label"}', 'content.form.meta', 'COLUMN', 0, NULL, NULL, NULL),
  ('content', 'content.form.titleLabelText', 'TEXT', '{"as":"span","text":"제목"}', 'content.form.titleLabel', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.form.titleInput', 'INPUT', '{"domId":"postTitle","inputType":"text","maxLength":180}', 'content.form.titleLabel', NULL, 1, NULL, NULL, NULL),
  ('content', 'content.form.visibilityLabel', 'GROUP', '{"as":"label"}', 'content.form.meta', 'COLUMN', 1, NULL, NULL, NULL),
  ('content', 'content.form.visibilityText', 'TEXT', '{"as":"span","text":"공개 범위"}', 'content.form.visibilityLabel', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.form.visibilityInput', 'SELECT', '{"domId":"postVisibility","value":"private","options":[{"value":"private","label":"비공개"},{"value":"team","label":"팀"},{"value":"public","label":"공개"}]}', 'content.form.visibilityLabel', NULL, 1, NULL, NULL, NULL),
  ('content', 'content.form.tagsLabel', 'TEXT', '{"as":"label","className":"field-label","text":"태그"}', 'content.form.panel', NULL, 2, NULL, NULL, NULL),
  ('content', 'content.form.tagsInput', 'INPUT', '{"domId":"postTags","inputType":"text","placeholder":"쉼표로 구분"}', 'content.form.panel', NULL, 3, NULL, NULL, NULL),
  ('content', 'content.form.bodyLabel', 'TEXT', '{"as":"label","className":"field-label","text":"본문"}', 'content.form.panel', NULL, 4, NULL, NULL, NULL),
  ('content', 'content.form.bodyInput', 'TEXTAREA', '{"domId":"postBody","rows":12}', 'content.form.panel', NULL, 5, NULL, NULL, NULL),
  ('content', 'content.form.assetLabel', 'TEXT', '{"as":"label","className":"field-label","text":"첨부 파일"}', 'content.form.panel', NULL, 6, NULL, NULL, NULL),
  ('content', 'content.form.assetInput', 'FILE_INPUT', '{"domId":"postAssets","multiple":true}', 'content.form.panel', NULL, 7, NULL, NULL, NULL),
  ('content', 'content.form.actions', 'GROUP', '{"className":"result-actions"}', 'content.form.panel', 'ROW', 8, NULL, NULL, NULL),
  ('content', 'content.form.save', 'BUTTON', '{"domId":"btnSavePost","className":"btn btn-primary","text":"저장"}', 'content.form.actions', NULL, 0, 'SAVE_CONTENT_POST', NULL, NULL),
  ('content', 'content.form.delete', 'BUTTON', '{"domId":"btnDeletePost","className":"btn btn-ghost","text":"삭제","disabled":true}', 'content.form.actions', NULL, 1, 'DELETE_CONTENT_POST', NULL, NULL),
  ('content', 'content.form.status', 'TEXT', '{"as":"span","domId":"postStatus","className":"hint","text":""}', 'content.form.actions', NULL, 2, NULL, NULL, NULL),

  ('content', 'content.list.panel', 'GROUP', '{"as":"section","className":"panel"}', 'content.member', 'COLUMN', 1, NULL, NULL, NULL),
  ('content', 'content.list.head', 'GROUP', '{"className":"result-head"}', 'content.list.panel', 'ROW', 0, NULL, NULL, NULL),
  ('content', 'content.list.copy', 'GROUP', '{}', 'content.list.head', 'COLUMN', 0, NULL, NULL, NULL),
  ('content', 'content.list.label', 'TEXT', '{"as":"div","className":"field-label","text":"콘텐츠 목록"}', 'content.list.copy', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.list.hint', 'TEXT', '{"as":"p","className":"hint","text":"최근 수정순으로 표시합니다."}', 'content.list.copy', NULL, 1, NULL, NULL, NULL),
  ('content', 'content.list.reload', 'BUTTON', '{"domId":"btnReloadPosts","className":"btn btn-ghost btn-small","text":"새로고침"}', 'content.list.head', NULL, 1, 'LOAD_CONTENT_POSTS', NULL, NULL),
  ('content', 'content.list.body', 'GROUP', '{"domId":"postList","className":"post-list"}', 'content.list.panel', 'COLUMN', 1, NULL, NULL, NULL),
  ('content', 'content.assets.panel', 'GROUP', '{"domId":"assetPanel","className":"asset-panel","hidden":true}', 'content.list.panel', 'COLUMN', 2, NULL, NULL, NULL),
  ('content', 'content.assets.label', 'TEXT', '{"as":"div","className":"field-label","text":"첨부 파일"}', 'content.assets.panel', NULL, 0, NULL, NULL, NULL),
  ('content', 'content.assets.list', 'GROUP', '{"domId":"assetList","className":"asset-list"}', 'content.assets.panel', 'COLUMN', 1, NULL, NULL, NULL),
  ('content', 'content.foot', 'TEXT', '{"as":"p","className":"foot","text":"기획 허널 루프"}', 'content.root', NULL, 4, NULL, NULL, NULL),

  ('time-settings', 'time.root', 'GROUP', '{"className":"sdui-root"}', NULL, 'COLUMN', 0, NULL, NULL, NULL),
  ('time-settings', 'time.title', 'TEXT', '{"as":"h1","text":"시간 설정"}', 'time.root', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.lead', 'GROUP', '{"as":"p","className":"lead"}', 'time.root', 'ROW', 1, NULL, NULL, NULL),
  ('time-settings', 'time.lead.text', 'TEXT', '{"as":"span","text":"기본 근무 시간과 날짜별 시간 블록을 관리합니다. "}', 'time.lead', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.lead.usage', 'TEXT', '{"as":"span","className":"usage-pill","text":"...","dataset":{"usage":""}}', 'time.lead', NULL, 1, NULL, NULL, NULL),

  ('time-settings', 'time.guest', 'GROUP', '{"as":"section","domId":"guest","className":"panel","hidden":true}', 'time.root', 'COLUMN', 2, NULL, NULL, NULL),
  ('time-settings', 'time.guest.row', 'GROUP', '{"className":"empty-login"}', 'time.guest', 'ROW', 0, NULL, NULL, NULL),
  ('time-settings', 'time.guest.copy', 'TEXT', '{"as":"p","className":"hint","text":"시간 설정은 로그인 후 사용할 수 있습니다."}', 'time.guest.row', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.guest.login', 'TEXT', '{"as":"span","domId":"guestLogin","text":""}', 'time.guest.row', NULL, 1, NULL, NULL, NULL),

  ('time-settings', 'time.member', 'GROUP', '{"as":"section","domId":"member","hidden":true}', 'time.root', 'COLUMN', 3, NULL, NULL, NULL),
  ('time-settings', 'time.grid', 'GROUP', '{"className":"grid2"}', 'time.member', 'ROW', 0, NULL, NULL, NULL),
  ('time-settings', 'time.settings.panel', 'GROUP', '{"as":"section","className":"panel"}', 'time.grid', 'COLUMN', 0, NULL, NULL, NULL),
  ('time-settings', 'time.settings.label', 'TEXT', '{"as":"div","className":"field-label","text":"기본 시간대"}', 'time.settings.panel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.settings.meta', 'GROUP', '{"className":"meta-grid"}', 'time.settings.panel', 'ROW', 1, NULL, NULL, NULL),
  ('time-settings', 'time.settings.tzLabel', 'GROUP', '{"as":"label"}', 'time.settings.meta', 'COLUMN', 0, NULL, NULL, NULL),
  ('time-settings', 'time.settings.tzText', 'TEXT', '{"as":"span","text":"타임존"}', 'time.settings.tzLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.settings.tzInput', 'INPUT', '{"domId":"timezone","inputType":"text","value":"Asia/Seoul","autocomplete":"off"}', 'time.settings.tzLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.settings.startLabel', 'GROUP', '{"as":"label"}', 'time.settings.meta', 'COLUMN', 1, NULL, NULL, NULL),
  ('time-settings', 'time.settings.startText', 'TEXT', '{"as":"span","text":"근무 시작"}', 'time.settings.startLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.settings.startInput', 'INPUT', '{"domId":"workdayStart","inputType":"time","value":"09:00"}', 'time.settings.startLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.settings.endLabel', 'GROUP', '{"as":"label"}', 'time.settings.meta', 'COLUMN', 2, NULL, NULL, NULL),
  ('time-settings', 'time.settings.endText', 'TEXT', '{"as":"span","text":"근무 종료"}', 'time.settings.endLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.settings.endInput', 'INPUT', '{"domId":"workdayEnd","inputType":"time","value":"18:00"}', 'time.settings.endLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.weekdays.label', 'TEXT', '{"as":"div","className":"field-label","text":"반복 요일"}', 'time.settings.panel', NULL, 2, NULL, NULL, NULL),
  ('time-settings', 'time.weekdays.row', 'GROUP', '{"domId":"weekdayRow","className":"weekday-row"}', 'time.settings.panel', 'ROW', 3, NULL, NULL, NULL),
  ('time-settings', 'time.weekday.mon', 'CHECKBOX', '{"className":"weekday-chip","variant":"plain","value":"1","label":"월"}', 'time.weekdays.row', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.weekday.tue', 'CHECKBOX', '{"className":"weekday-chip","variant":"plain","value":"2","label":"화"}', 'time.weekdays.row', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.weekday.wed', 'CHECKBOX', '{"className":"weekday-chip","variant":"plain","value":"3","label":"수"}', 'time.weekdays.row', NULL, 2, NULL, NULL, NULL),
  ('time-settings', 'time.weekday.thu', 'CHECKBOX', '{"className":"weekday-chip","variant":"plain","value":"4","label":"목"}', 'time.weekdays.row', NULL, 3, NULL, NULL, NULL),
  ('time-settings', 'time.weekday.fri', 'CHECKBOX', '{"className":"weekday-chip","variant":"plain","value":"5","label":"금"}', 'time.weekdays.row', NULL, 4, NULL, NULL, NULL),
  ('time-settings', 'time.weekday.sat', 'CHECKBOX', '{"className":"weekday-chip","variant":"plain","value":"6","label":"토"}', 'time.weekdays.row', NULL, 5, NULL, NULL, NULL),
  ('time-settings', 'time.weekday.sun', 'CHECKBOX', '{"className":"weekday-chip","variant":"plain","value":"0","label":"일"}', 'time.weekdays.row', NULL, 6, NULL, NULL, NULL),
  ('time-settings', 'time.settings.actions', 'GROUP', '{"className":"result-actions"}', 'time.settings.panel', 'ROW', 4, NULL, NULL, NULL),
  ('time-settings', 'time.settings.save', 'BUTTON', '{"domId":"btnSaveSettings","className":"btn btn-primary","text":"저장"}', 'time.settings.actions', NULL, 0, 'SAVE_TIME_SETTINGS', NULL, NULL),
  ('time-settings', 'time.settings.status', 'TEXT', '{"as":"span","domId":"settingsStatus","className":"hint","text":""}', 'time.settings.actions', NULL, 1, NULL, NULL, NULL),

  ('time-settings', 'time.block.panel', 'GROUP', '{"as":"section","className":"panel"}', 'time.grid', 'COLUMN', 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.head', 'GROUP', '{"className":"result-head"}', 'time.block.panel', 'ROW', 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.copy', 'GROUP', '{}', 'time.block.head', 'COLUMN', 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.label', 'TEXT', '{"as":"div","className":"field-label","text":"날짜별 블록"}', 'time.block.copy', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.hint', 'TEXT', '{"as":"p","className":"hint","text":"회의, 집중 시간, 바쁜 시간을 같은 날짜 안에서 기록합니다."}', 'time.block.copy', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.dateLabel', 'GROUP', '{"as":"label","className":"compact-label"}', 'time.block.head', 'COLUMN', 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.dateText', 'TEXT', '{"as":"span","text":"날짜"}', 'time.block.dateLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.dateInput', 'INPUT', '{"domId":"blockDate","inputType":"date"}', 'time.block.dateLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.meta', 'GROUP', '{"className":"meta-grid"}', 'time.block.panel', 'ROW', 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.startLabel', 'GROUP', '{"as":"label"}', 'time.block.meta', 'COLUMN', 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.startText', 'TEXT', '{"as":"span","text":"시작"}', 'time.block.startLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.startInput', 'INPUT', '{"domId":"blockStart","inputType":"time","value":"09:00"}', 'time.block.startLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.endLabel', 'GROUP', '{"as":"label"}', 'time.block.meta', 'COLUMN', 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.endText', 'TEXT', '{"as":"span","text":"종료"}', 'time.block.endLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.endInput', 'INPUT', '{"domId":"blockEnd","inputType":"time","value":"10:00"}', 'time.block.endLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.kindLabel', 'GROUP', '{"as":"label"}', 'time.block.meta', 'COLUMN', 2, NULL, NULL, NULL),
  ('time-settings', 'time.block.kindText', 'TEXT', '{"as":"span","text":"종류"}', 'time.block.kindLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.kindInput', 'SELECT', '{"domId":"blockKind","value":"available","options":[{"value":"available","label":"가능"},{"value":"busy","label":"바쁨"},{"value":"focus","label":"집중"},{"value":"meeting","label":"회의"}]}', 'time.block.kindLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.noteLabel', 'GROUP', '{"as":"label"}', 'time.block.meta', 'COLUMN', 3, NULL, NULL, NULL),
  ('time-settings', 'time.block.noteText', 'TEXT', '{"as":"span","text":"메모"}', 'time.block.noteLabel', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.block.noteInput', 'INPUT', '{"domId":"blockNote","inputType":"text","maxLength":240,"placeholder":"예: 고객 미팅"}', 'time.block.noteLabel', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.block.actions', 'GROUP', '{"className":"result-actions"}', 'time.block.panel', 'ROW', 2, NULL, NULL, NULL),
  ('time-settings', 'time.block.add', 'BUTTON', '{"domId":"btnAddBlock","className":"btn btn-primary","text":"블록 추가"}', 'time.block.actions', NULL, 0, 'CREATE_TIME_BLOCK', NULL, NULL),
  ('time-settings', 'time.block.status', 'TEXT', '{"as":"span","domId":"blockStatus","className":"hint","text":""}', 'time.block.actions', NULL, 1, NULL, NULL, NULL),

  ('time-settings', 'time.list.panel', 'GROUP', '{"as":"section","className":"panel"}', 'time.member', 'COLUMN', 1, NULL, NULL, NULL),
  ('time-settings', 'time.list.head', 'GROUP', '{"className":"result-head"}', 'time.list.panel', 'ROW', 0, NULL, NULL, NULL),
  ('time-settings', 'time.list.label', 'TEXT', '{"as":"div","className":"field-label","text":"선택 날짜 일정"}', 'time.list.head', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.list.reload', 'BUTTON', '{"domId":"btnReloadBlocks","className":"btn btn-ghost btn-small","text":"새로고침"}', 'time.list.head', NULL, 1, 'LOAD_TIME_BLOCKS', NULL, NULL),
  ('time-settings', 'time.table.wrap', 'GROUP', '{"className":"cost-table-wrap"}', 'time.list.panel', 'COLUMN', 1, NULL, NULL, NULL),
  ('time-settings', 'time.table', 'GROUP', '{"as":"table","className":"cost-table"}', 'time.table.wrap', 'COLUMN', 0, NULL, NULL, NULL),
  ('time-settings', 'time.thead', 'GROUP', '{"as":"thead"}', 'time.table', 'COLUMN', 0, NULL, NULL, NULL),
  ('time-settings', 'time.head.row', 'GROUP', '{"as":"tr"}', 'time.thead', 'ROW', 0, NULL, NULL, NULL),
  ('time-settings', 'time.head.time', 'TEXT', '{"as":"th","text":"시간"}', 'time.head.row', NULL, 0, NULL, NULL, NULL),
  ('time-settings', 'time.head.kind', 'TEXT', '{"as":"th","text":"종류"}', 'time.head.row', NULL, 1, NULL, NULL, NULL),
  ('time-settings', 'time.head.note', 'TEXT', '{"as":"th","text":"메모"}', 'time.head.row', NULL, 2, NULL, NULL, NULL),
  ('time-settings', 'time.head.manage', 'TEXT', '{"as":"th","text":"관리"}', 'time.head.row', NULL, 3, NULL, NULL, NULL),
  ('time-settings', 'time.rows', 'GROUP', '{"as":"tbody","domId":"blockRows"}', 'time.table', 'COLUMN', 1, NULL, NULL, NULL),
  ('time-settings', 'time.foot', 'TEXT', '{"as":"p","className":"foot","text":"기획 허널 루프"}', 'time.root', NULL, 4, NULL, NULL, NULL);
